### ISSUE TITLE
[FEAT] 학사 개인정보 추가 및 회원 로직 변경

### ISSUE THREAD

**Issue by leehjhjhj** [LikeLion-11th-Domtory/Domtory_Server#40]
## To do
- [x] 학사 개인정보 테이블 추가
- [x] S3에 엑셀 파일 업로드 -> Lambda 에서 학사 개인정보 테이블 반영 
- [x] 회원 테이블 변경
- [x] 회원 가입 로직 변경 -> 학사 개인정보 베이스 회원 자동 생성
- [x] excel 테이블 생성해서 admin에서 엑셀 파일 업로드시 S3에 자동으로 업로드
## Member 테이블 변경 관련
![image](https://github.com/LikeLion-11th-Domtory/Domtory_Server/assets/102458609/1bab7898-6719-4e7c-aa73-7d4c5bdc0fde)
```
Table member {
  id int [pk, increment]
  username string
  password string
  phone_number string
  name string
  birthday string [note: 'ex) 980614']
  status boolean [default:`ACTIVE`, note: 'ACTIVE, BANNED, WITHDRAWAL']
}
```
### 변경점
- `email` -> `username`으로 변경. `username`은 학사 코드로 자동 생성(ex: 231234)
- `nickname` 삭제
- `dormitory_card` 삭제
- `created_at` 삭제
- `status`에서 `ADMIN_VERIFICATION_PENDING` 삭제
- `birthday`를 datetime 필드에서 string으로 변경(ex: 980614)

**Comment by ShinSub98** [comment]
확인했습니다
이렇게 바뀌면 게시판쪽은 거의 변동 없을 것 같습니다

**Comment by Chaeyoung714** [comment]
확인했습니다 저도 괜찮습니다!
